// js/search.js
// Requires window.LAB_INDEX to exist (generated by repo-indexer)
(function(){
  // Wait until LAB_INDEX exists
  function ready(cb){
    if(window.LAB_INDEX) return cb();
    setTimeout(()=>ready(cb), 150);
  }

  ready(()=>{
    const options = {
      keys: ['title','description','tags'],
      threshold: 0.35,
      includeScore: true,
      useExtendedSearch: true
    };
    const fuse = new Fuse(window.LAB_INDEX.items, options);
    const input = document.getElementById('global-search');
    const resultsBox = document.getElementById('search-results');
    input.addEventListener('input', e=>{
      const q = e.target.value.trim();
      if(!q){ resultsBox.innerHTML = ''; return; }
      const results = fuse.search(q).slice(0,50);
      resultsBox.innerHTML = '';
      results.forEach(r=>{
        const it = r.item;
        const li = document.createElement('li');
        li.className = 'list-item';
        li.innerHTML = `<a href="${it.path}" class="card-link"><div class="card"><h4>${escapeHtml(it.title)}</h4><p>${escapeHtml(it.description||'')}</p><div class="meta">${(it.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join(' ')}</div></div></a>`;
        resultsBox.appendChild(li);
      });
    });
  });

  function escapeHtml(s){ if(!s) return ''; return s.replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
})();